### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by provinceinnovation** [scoutapp/scout_apm_node#239]
Found a memory leak in this `@scout_apm/scout-apm` module.

Reproducible example below:
```
const express = require('express');
const scout = require('@scout_apm/scout-apm');

const server = express();

server.use(scout.expressMiddleware());

server.get('/leak', (req, res) => {
  res.status(200).send('sending requests to this endpoint causes memory leak');
});

return scout.install({
  allowShutdown: true,
  monitor: true,
  name: 'example-app',
  key: 'examplekey',
})
  .then(() => {
    console.log('installed scout apm');
    server.listen(3000, () => console.log('server started on port 3000'));
  });
```

I start the server take a memory snapshot, then I made 1026 requests using the `siege` (HTTP load test library) to the `http://localhost:3000/leak` endpoint. The heap grew from `8.3MB` to `31.7MB`. See screenshot below:

<img width="1308" alt="Screenshot 2020-09-19 at 22 05 36" src="https://user-images.githubusercontent.com/69924001/93689275-da3a2880-fac4-11ea-9081-4a82426e7721.png">

This has also been causing my production app to continually crash - see screenshot below showing before & after of disabling  `scout_apm_node`.

<img width="209" alt="Screenshot 2020-09-19 at 22 11 39" src="https://user-images.githubusercontent.com/69924001/93689327-76fcc600-fac5-11ea-8acc-2ac89cb424bd.png">

**Comment by vados-scout** [comment]
Hi @provinceinnovation thank you for reporting this -- I've started investigating and will release a fix ASAP!

**Comment by vados-scout** [comment]
Hey @provinceinnovation I got a chance to take a look at the memory leak issue and some other things since that was most pressing and I have a RC candidate (v0.2.0-rc.0) if you would mind giving it a shot.

You can find the release on NPM here -> https://www.npmjs.com/package/@scout_apm/scout-apm/v/0.2.0-rc.0

**Comment by provinceinnovation** [comment]
Hi @vados-scout, looks like this has fixed the memory leak from my brief testing. Unfortunately `scout_apm_node` is not useful to me as it is unable to monitor my endpoints (cc #238 ). Therefore, I will not be using it in my production environment.
Thanks

**Comment by vados-scout** [comment]
Hi @provinceinnovation appreciate the confirmation. I'm glad that was at least able to be resolved.

I'm sorry to hear you won't be using scout due to `Router`s not being covered in the agent beta `express` integration (@cschneid  @dlanderson) -- this is a fix that we're planning to release within the week. There are lots of ways to use `express` and this way (at least) should have been covered and will be as soon as possible. If there are any other things that would have made your experience better I'd love to hear about it.

Thanks
